# coding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


SystemParam.create([{ key: :smdlv, value_type: :currency, value: '24590.6', version: '2017', state: :active },
                   { key: :fosyga, value_type: :percent, value: '50', version: '2017', state: :active },
                   { key: :runt, value_type: :currency, value: '1610', version: '2017', state: :active }])

vc1 = VehicleClass.create(name: 'MOTOS', has_age: false)
vc2 = VehicleClass.create(name: 'CAMPEROS Y CAMIONETAS', has_age: true)
vc3 = VehicleClass.create(name: 'CARGA O MIXTO', has_age: false)
vc4 = VehicleClass.create(name: 'OFICIALES ESPECIALES ', has_age: false)
vc5 = VehicleClass.create(name: 'AUTOS FAMILIARES', has_age: true)
vc6 = VehicleClass.create(name: 'VEHICULOS PARA SEIS O MAS PASAJEROS', has_age: true)
vc7 = VehicleClass.create(name: 'AUTOS DE NEGOCIOS Y TAXIS', has_age: true)
vc8 = VehicleClass.create(name: 'BUSES Y BUSETAS DE SERVICIO PUBLICO URBANO', has_age: false)
vc9 = VehicleClass.create(name: 'SERVICIO PUBLICO INTERMUNICIPAL', has_age: false)

st1 = SubType.create(name: 'Menos de 100 c.c.')
st2 = SubType.create(name: 'De 100 a 200 c.c.')
st3 = SubType.create(name: 'Más de 200 c.c.')
st4 = SubType.create(name: 'MOTOCARROS')
st5 = SubType.create(name: 'Menos de 1500 c.c.')
st6 = SubType.create(name: '1500 a 2500 ')
st7 = SubType.create(name: 'Más de 2500 c.c')
st8 = SubType.create(name: 'Menos de 5 toneladas ')
st9 = SubType.create(name: 'De 5 a 15 toneladas ')
st10 = SubType.create(name: 'Más de 15 toneladas')
st11 = SubType.create(name: 'Menos de 2500')
st12 = SubType.create(name: '2500 o más')
st13 = SubType.create(name: 'Menor 10 pasajeros')
st14 = SubType.create(name: '10 o más pasajeros')
st15 = SubType.create(name: 'N/A')

c1 = Classification.create(vehicle_class_id: vc1.id, sub_type_id: st1.id)
c2 = Classification.create(vehicle_class_id: vc1.id, sub_type_id: st2.id)
c3 = Classification.create(vehicle_class_id: vc1.id, sub_type_id: st3.id)
c4 = Classification.create(vehicle_class_id: vc1.id, sub_type_id: st4.id)
c5 = Classification.create(vehicle_class_id: vc2.id, sub_type_id: st5.id)
c6 = Classification.create(vehicle_class_id: vc2.id, sub_type_id: st6.id)
c7 = Classification.create(vehicle_class_id: vc2.id, sub_type_id: st7.id)
c8 = Classification.create(vehicle_class_id: vc3.id, sub_type_id: st8.id)
c9 = Classification.create(vehicle_class_id: vc3.id, sub_type_id: st9.id)
c10 = Classification.create(vehicle_class_id: vc3.id, sub_type_id: st10.id)
c11 = Classification.create(vehicle_class_id: vc4.id, sub_type_id: st5.id)
c12 = Classification.create(vehicle_class_id: vc4.id, sub_type_id: st6.id)
c13 = Classification.create(vehicle_class_id: vc4.id, sub_type_id: st7.id)
c14 = Classification.create(vehicle_class_id: vc5.id, sub_type_id: st5.id)
c15 = Classification.create(vehicle_class_id: vc5.id, sub_type_id: st6.id)
c16 = Classification.create(vehicle_class_id: vc5.id, sub_type_id: st7.id)
c17 = Classification.create(vehicle_class_id: vc6.id, sub_type_id: st11.id)
c18 = Classification.create(vehicle_class_id: vc6.id, sub_type_id: st12.id)
c19 = Classification.create(vehicle_class_id: vc7.id, sub_type_id: st5.id)
c20 = Classification.create(vehicle_class_id: vc7.id, sub_type_id: st6.id)
c21 = Classification.create(vehicle_class_id: vc7.id, sub_type_id: st7.id)
c22 = Classification.create(vehicle_class_id: vc8.id, sub_type_id: st15.id)
c23 = Classification.create(vehicle_class_id: vc9.id, sub_type_id: st13.id)
c24 = Classification.create(vehicle_class_id: vc9.id, sub_type_id: st14.id)

ar1 = AgeRange.create(name: '0 a 9 años', min: 0, max: 9)
ar2 = AgeRange.create(name: '10 años o mas', min: 10, max: 1000)
ar3 = AgeRange.create(name: 'N/A')

Rate.create(code: 110, value: 8.26,  classification_id: c1.id, age_range_id: ar3.id)
Rate.create(code: 120, value: 11.09,  classification_id: c2.id, age_range_id: ar3.id)
Rate.create(code: 130, value: 12.51,  classification_id: c3.id, age_range_id: ar3.id)
Rate.create(code: 140, value: 12.51,  classification_id: c4.id, age_range_id: ar3.id)
Rate.create(code: 211, value: 13.29,  classification_id: c5.id, age_range_id: ar1.id)
Rate.create(code: 212, value: 15.99,  classification_id: c5.id, age_range_id: ar2.id)
Rate.create(code: 221, value: 15.88,  classification_id: c6.id, age_range_id: ar1.id)
Rate.create(code: 222, value: 18.82,  classification_id: c6.id, age_range_id: ar2.id)
Rate.create(code: 231, value: 18.63,  classification_id: c7.id, age_range_id: ar1.id)
Rate.create(code: 232, value: 21.39,  classification_id: c7.id, age_range_id: ar2.id)
Rate.create(code: 310, value: 14.90,  classification_id: c8.id, age_range_id: ar3.id)
Rate.create(code: 320, value: 21.53,  classification_id: c9.id, age_range_id: ar3.id)
Rate.create(code: 330, value: 27.23,  classification_id: c10.id, age_range_id: ar3.id)
Rate.create(code: 410, value: 16.77,  classification_id: c11.id, age_range_id: ar3.id)
Rate.create(code: 420, value: 21.15,  classification_id: c12.id, age_range_id: ar3.id)
Rate.create(code: 430, value: 25.36,  classification_id: c13.id, age_range_id: ar3.id)
Rate.create(code: 511, value: 7.48,  classification_id: c14.id, age_range_id: ar1.id)
Rate.create(code: 512, value: 9.93,  classification_id: c14.id, age_range_id: ar2.id)
Rate.create(code: 521, value: 9.12,  classification_id: c15.id, age_range_id: ar1.id)
Rate.create(code: 522, value: 11.35,  classification_id: c15.id, age_range_id: ar2.id)
Rate.create(code: 531, value: 10.66,  classification_id: c16.id, age_range_id: ar1.id)
Rate.create(code: 532, value: 12.65,  classification_id: c16.id, age_range_id: ar2.id)
Rate.create(code: 611, value: 13.37,  classification_id: c17.id, age_range_id: ar1.id)
Rate.create(code: 612, value: 17.08,  classification_id: c17.id, age_range_id: ar2.id)
Rate.create(code: 621, value: 17.91,  classification_id: c18.id, age_range_id: ar1.id)
Rate.create(code: 622, value: 21.51,  classification_id: c18.id, age_range_id: ar2.id)
Rate.create(code: 711, value: 9.28,  classification_id:  c19.id, age_range_id: ar1.id)
Rate.create(code: 712, value: 11.60,  classification_id: c19.id, age_range_id: ar2.id)
Rate.create(code: 721, value: 11.54,  classification_id: c20.id, age_range_id: ar1.id)
Rate.create(code: 722, value: 14.27,  classification_id: c20.id, age_range_id: ar2.id)
Rate.create(code: 731, value: 14.90,  classification_id: c21.id, age_range_id: ar1.id)
Rate.create(code: 732, value: 17.49,  classification_id: c21.id, age_range_id: ar2.id)
Rate.create(code: 810, value: 21.81,  classification_id: c22.id, age_range_id: ar3.id)
Rate.create(code: 910, value: 22.01,  classification_id: c23.id, age_range_id: ar3.id)
Rate.create(code: 920, value: 31.96,  classification_id: c24.id, age_range_id: ar3.id)
